safe:         true
lsi:          false
highlighter:  pygments
url:          http://apiblueprint.org
include:      ['favicon.png', 'favicon.ico', 'apple-touch-icon-precomposed.png']
exclude:      ['*.styl', '*.coffee', 'node_modules']
